much prettier, still needs organization
Fritzzzz1/PVP_Wordle-BackEnd pull request #2
Opened 2022-05-02 09:35 UTC by Fritzzzz1

2022-05-02 13:08 UTC, TamirOr requested changes
codes look good.
check about .gitignore and add it,  I don't think you need to push __pycache__ files.

2022-05-02 13:08 UTC, TamirOr commented on games/helpers.py
> +from PVP_WORDLE_BackEnd.helpers import check_and_save_serializer
I think PVP_WORDLE_BackEnd should be as package name - pvp_wordle_backend

2022-05-02 13:08 UTC, TamirOr commented on games/helpers.py
> +def handle_create_new_game(request_data, player_id):
Try to think of a better name for this function | create_game

2022-05-02 13:08 UTC, TamirOr commented on games/helpers.py
> +        attempts = [{'board': board_pk_or_errors, 'word': words[i - 1]} for i in range(1, len(words) + 1)]
you dirty one ;)

2022-05-02 13:08 UTC, TamirOr commented on pvp_wordle_backend/helpers.py
> +            return 1
change to ENUM(1 isn't informative enough)

2022-05-02 13:08 UTC, TamirOr commented on boards/serializer.py
> +        fields = '__all__'
oh-hh so sophisticated

2022-05-02 13:08 UTC, TamirOr commented on players/urls.py
> +    # path('<int:player_id>/games/<int:game_id>', player_game_detail, name='player-game-detail'),
Do not push comment-out lines

2022-05-02 13:38 UTC, Fritzzzz1 commented on games/helpers.py
> +        attempts = [{'board': board_pk_or_errors, 'word': words[i - 1]} for i in range(1, len(words) + 1)]
i dont get it

2022-05-02 13:45 UTC, TamirOr commented on games/helpers.py
> +        attempts = [{'board': board_pk_or_errors, 'word': words[i - 1]} for i in range(1, len(words) + 1)]
I like what you wrote here

2022-05-02 13:47 UTC, Fritzzzz1 commented on games/helpers.py
> +        attempts = [{'board': board_pk_or_errors, 'word': words[i - 1]} for i in range(1, len(words) + 1)]
thank you

2022-05-02 13:49 UTC, Fritzzzz1 commented on pvp_wordle_backend/helpers.py
> +            return 1
maybe True is good? or also not enough.

2022-05-03 15:22 UTC, TamirOr approved these changes

2022-05-03 15:22 UTC, TamirOr commented on players/views.py
> +class GetToken(TokenObtainPairView):
Is it a view function?

2022-05-03 15:22 UTC, TamirOr commented on players/views.py
> +        player['games'] = len(Player.objects.get(pk=player['pk']).game.all())
to me, map function is more readable then for loop.
for example:
    serializer.data.map(lambda player: player.update(games=len(Player.objects.get(pk=player['pk']).game.all())))

2022-05-03 15:24 UTC, Fritzzzz1 commented on players/views.py
> +class GetToken(TokenObtainPairView):
it is a class based view, used as a view function in players.urls with as_view()

2022-05-03 15:27 UTC, Fritzzzz1 commented on players/views.py
> +        player['games'] = len(Player.objects.get(pk=player['pk']).game.all())
you dirty dirty saying you don't really know python

2022-05-03 15:39 UTC, TamirOr commented on players/views.py
> +        player['games'] = len(Player.objects.get(pk=player['pk']).game.all())
:)

2022-05-06 13:15 UTC, merged